default_platform(:ios)

APP_IDENTIFIER = "jp.sukari.app"

platform :ios do
  desc "Upload metadata only"
  lane :upload_metadata do
    api_key = app_store_connect_api_key(
      key_id: "4V6TM3V62F",
      issuer_id: "8735be2b-b7b2-461f-8dad-7791de1f4dc7",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_4V6TM3V62F.p8"),
      duration: 1200,
      in_house: false
    )
    deliver(
      api_key: api_key,
      app_identifier: APP_IDENTIFIER,
      skip_binary_upload: true,
      skip_screenshots: true,
      skip_metadata: false,
      metadata_path: "./fastlane/metadata",
      submit_for_review: false,
      force: true,
      precheck_include_in_app_purchases: false
    )
  end

  desc "Upload screenshots only"
  lane :upload_screenshots do
    api_key = app_store_connect_api_key(
      key_id: "4V6TM3V62F",
      issuer_id: "8735be2b-b7b2-461f-8dad-7791de1f4dc7",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_4V6TM3V62F.p8"),
      duration: 1200,
      in_house: false
    )
    deliver(
      api_key: api_key,
      app_identifier: APP_IDENTIFIER,
      skip_binary_upload: true,
      skip_screenshots: false,
      skip_metadata: true,
      screenshots_path: "./fastlane/screenshots",
      overwrite_screenshots: true,
      submit_for_review: false,
      force: true,
      precheck_include_in_app_purchases: false
    )
  end

  desc "Upload metadata, screenshots and submit for review"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "4V6TM3V62F",
      issuer_id: "8735be2b-b7b2-461f-8dad-7791de1f4dc7",
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_4V6TM3V62F.p8"),
      duration: 1200,
      in_house: false
    )

    deliver(
      api_key: api_key,
      app_identifier: APP_IDENTIFIER,
      skip_binary_upload: true,
      skip_screenshots: false,
      skip_metadata: false,
      screenshots_path: "./fastlane/screenshots",
      metadata_path: "./fastlane/metadata",
      copyright: "© 2026 Kazuki Yamada",
      app_rating_config_path: "./fastlane/age_rating_config.json",
      primary_category: "SHOPPING",
      automatic_release: false,
      submit_for_review: true,
      force: true,
      precheck_include_in_app_purchases: false,
      app_review_information: {
        first_name: "Kazuki",
        last_name: "Yamada",
        phone_number: "+81 80 5773 7678",
        email_address: "1sukari.app@gmail.com",
        notes: "No account login required. Scan a barcode or search by text to compare prices across Amazon, Rakuten, Yahoo Shopping, Mercari, and Yahuoku. Free tier: 10 scans/day. Premium: unlimited scans."
      },
      submission_information: {
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: true,
        add_id_info_uses_idfa: false,
        content_rights_has_rights: true,
        content_rights_contains_third_party_content: false,
      }
    )
  end
end
